import mongoose from "mongoose";
import { Food } from "../models/Food.js";

// Indian Foods with accurate nutritional values (per 100g unless specified)
const indianFoods = [
  // Grains & Cereals
  {
    name: "Basmati Rice",
    category: "Grains",
    servingSize: 100,
    servingUnit: "g",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    calcium: 10,
    iron: 0.8,
    sodium: 1,
    potassium: 115,
    vitaminC: 0,
    vitaminA: 0,
    description: "Long-grain basmati rice (cooked)",
  },
  {
    name: "Brown Rice",
    category: "Grains",
    servingSize: 100,
    servingUnit: "g",
    calories: 112,
    protein: 2.6,
    carbs: 24,
    fat: 0.9,
    fiber: 1.8,
    calcium: 23,
    iron: 0.8,
    sodium: 7,
    potassium: 150,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    name: "Whole Wheat Roti",
    category: "Grains",
    servingSize: 60,
    servingUnit: "piece",
    calories: 155,
    protein: 5,
    carbs: 30,
    fat: 1.5,
    fiber: 4,
    calcium: 50,
    iron: 2.5,
    sodium: 200,
    potassium: 150,
    vitaminC: 0,
    vitaminA: 0,
    description: "One whole wheat roti (approximately 60g)",
  },
  {
    name: "Naan Bread",
    category: "Grains",
    servingSize: 90,
    servingUnit: "piece",
    calories: 262,
    protein: 8,
    carbs: 45,
    fat: 5.5,
    fiber: 1.5,
    calcium: 100,
    iron: 2,
    sodium: 500,
    potassium: 100,
    vitaminC: 0,
    vitaminA: 0,
    description: "One piece of naan bread",
  },
  {
    name: "Oats",
    category: "Grains",
    servingSize: 50,
    servingUnit: "g",
    calories: 195,
    protein: 8.5,
    carbs: 33,
    fat: 3.5,
    fiber: 5.3,
    calcium: 27,
    iron: 2.1,
    sodium: 1,
    potassium: 214,
    vitaminC: 0,
    vitaminA: 0,
  },

  // Proteins - Meat
  {
    name: "Chicken Breast",
    category: "Proteins",
    servingSize: 100,
    servingUnit: "g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    calcium: 15,
    iron: 0.4,
    sodium: 74,
    potassium: 256,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    name: "Mutton/Goat Meat",
    category: "Proteins",
    servingSize: 100,
    servingUnit: "g",
    calories: 159,
    protein: 26,
    carbs: 0,
    fat: 6.3,
    fiber: 0,
    calcium: 18,
    iron: 3.2,
    sodium: 75,
    potassium: 280,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    name: "Fish (Rohu)",
    category: "Proteins",
    servingSize: 100,
    servingUnit: "g",
    calories: 94,
    protein: 20,
    carbs: 0,
    fat: 1.3,
    fiber: 0,
    calcium: 25,
    iron: 1.5,
    sodium: 80,
    potassium: 290,
    vitaminC: 0,
    vitaminA: 200,
  },
  {
    name: "Egg",
    category: "Proteins",
    servingSize: 50,
    servingUnit: "piece",
    calories: 77,
    protein: 6.5,
    carbs: 0.6,
    fat: 5.5,
    fiber: 0,
    calcium: 28,
    iron: 0.9,
    sodium: 71,
    potassium: 73,
    vitaminC: 0,
    vitaminA: 270,
  },
  {
    name: "Paneer (Indian Cottage Cheese)",
    category: "Proteins",
    servingSize: 100,
    servingUnit: "g",
    calories: 265,
    protein: 25,
    carbs: 3.2,
    fat: 20,
    fiber: 0,
    calcium: 390,
    iron: 0.4,
    sodium: 480,
    potassium: 65,
    vitaminC: 0,
    vitaminA: 300,
  },
  {
    name: "Moong Dal",
    category: "Proteins",
    servingSize: 100,
    servingUnit: "g",
    calories: 105,
    protein: 7.5,
    carbs: 19.3,
    fat: 0.4,
    fiber: 4,
    calcium: 35,
    iron: 1.4,
    sodium: 2,
    potassium: 266,
    vitaminC: 1.5,
    vitaminA: 22,
  },
  {
    name: "Chana Dal",
    category: "Proteins",
    servingSize: 100,
    servingUnit: "g",
    calories: 120,
    protein: 8,
    carbs: 22,
    fat: 0.5,
    fiber: 3.5,
    calcium: 40,
    iron: 1.6,
    sodium: 5,
    potassium: 300,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    name: "Rajma (Kidney Beans)",
    category: "Proteins",
    servingSize: 100,
    servingUnit: "g",
    calories: 127,
    protein: 8.7,
    carbs: 23,
    fat: 0.3,
    fiber: 4.3,
    calcium: 65,
    iron: 2.5,
    sodium: 2,
    potassium: 350,
    vitaminC: 1.5,
    vitaminA: 0,
  },

  // Vegetables
  {
    name: "Spinach (Palak)",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 23,
    protein: 2.7,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    calcium: 99,
    iron: 2.7,
    sodium: 79,
    potassium: 558,
    vitaminC: 28,
    vitaminA: 6300,
  },
  {
    name: "Tomato",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    calcium: 12,
    iron: 0.3,
    sodium: 5,
    potassium: 237,
    vitaminC: 14,
    vitaminA: 833,
  },
  {
    name: "Onion",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 40,
    protein: 1.1,
    carbs: 9,
    fat: 0.1,
    fiber: 1.7,
    calcium: 23,
    iron: 0.2,
    sodium: 4,
    potassium: 146,
    vitaminC: 7,
    vitaminA: 0,
  },
  {
    name: "Brinjal (Eggplant)",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 25,
    protein: 1,
    carbs: 6,
    fat: 0.2,
    fiber: 3,
    calcium: 12,
    iron: 0.3,
    sodium: 2,
    potassium: 229,
    vitaminC: 3.5,
    vitaminA: 25,
  },
  {
    name: "Potato",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    fiber: 2.1,
    calcium: 12,
    iron: 0.8,
    sodium: 6,
    potassium: 425,
    vitaminC: 20,
    vitaminA: 2,
  },
  {
    name: "Cauliflower",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 25,
    protein: 1.9,
    carbs: 5,
    fat: 0.3,
    fiber: 2.4,
    calcium: 22,
    iron: 0.4,
    sodium: 52,
    potassium: 303,
    vitaminC: 46,
    vitaminA: 22,
  },
  {
    name: "Bell Pepper",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 31,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 2,
    calcium: 10,
    iron: 0.3,
    sodium: 3,
    potassium: 175,
    vitaminC: 80,
    vitaminA: 2830,
  },
  {
    name: "Cabbage",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 25,
    protein: 1.3,
    carbs: 5.8,
    fat: 0.1,
    fiber: 2.4,
    calcium: 49,
    iron: 0.4,
    sodium: 16,
    potassium: 246,
    vitaminC: 36.6,
    vitaminA: 98,
  },

  // Fruits (Indian)
  {
    name: "Mango",
    category: "Fruits",
    servingSize: 165,
    servingUnit: "piece",
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.3,
    fiber: 1.6,
    calcium: 11,
    iron: 0.2,
    sodium: 2,
    potassium: 168,
    vitaminC: 36,
    vitaminA: 3894,
  },
  {
    name: "Banana",
    category: "Fruits",
    servingSize: 118,
    servingUnit: "piece",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    calcium: 5,
    iron: 0.3,
    sodium: 1,
    potassium: 358,
    vitaminC: 8.7,
    vitaminA: 64,
  },
  {
    name: "Papaya",
    category: "Fruits",
    servingSize: 152,
    servingUnit: "piece",
    calories: 43,
    protein: 0.7,
    carbs: 11,
    fat: 0.3,
    fiber: 1.7,
    calcium: 20,
    iron: 0.3,
    sodium: 8,
    potassium: 182,
    vitaminC: 61,
    vitaminA: 950,
  },
  {
    name: "Guava",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 68,
    protein: 2.6,
    carbs: 14,
    fat: 0.6,
    fiber: 5.4,
    calcium: 18,
    iron: 0.3,
    sodium: 2,
    potassium: 417,
    vitaminC: 228,
    vitaminA: 374,
  },
  {
    name: "Watermelon",
    category: "Fruits",
    servingSize: 152,
    servingUnit: "piece",
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    fiber: 0.4,
    calcium: 8,
    iron: 0.2,
    sodium: 1,
    potassium: 112,
    vitaminC: 8.4,
    vitaminA: 569,
  },
  {
    name: "Orange",
    category: "Fruits",
    servingSize: 131,
    servingUnit: "piece",
    calories: 47,
    protein: 0.7,
    carbs: 12,
    fat: 0.3,
    fiber: 2.4,
    calcium: 40,
    iron: 0.1,
    sodium: 0,
    potassium: 181,
    vitaminC: 53,
    vitaminA: 225,
  },

  // Dairy
  {
    name: "Milk (Whole)",
    category: "Dairy",
    servingSize: 244,
    servingUnit: "ml",
    calories: 149,
    protein: 7.7,
    carbs: 11.7,
    fat: 8,
    fiber: 0,
    calcium: 276,
    iron: 0.07,
    sodium: 107,
    potassium: 322,
    vitaminC: 0,
    vitaminA: 500,
  },
  {
    name: "Yogurt",
    category: "Dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0,
    calcium: 121,
    iron: 0.1,
    sodium: 59,
    potassium: 155,
    vitaminC: 0.3,
    vitaminA: 109,
  },
  {
    name: "Ghee (Clarified Butter)",
    category: "Dairy",
    servingSize: 14,
    servingUnit: "g",
    calories: 120,
    protein: 0,
    carbs: 0,
    fat: 13.6,
    fiber: 0,
    calcium: 5,
    iron: 0,
    sodium: 0,
    potassium: 5,
    vitaminC: 0,
    vitaminA: 676,
  },

  // Nuts & Seeds
  {
    name: "Almonds",
    category: "Nuts",
    servingSize: 28,
    servingUnit: "g",
    calories: 164,
    protein: 6,
    carbs: 6,
    fat: 14,
    fiber: 3.5,
    calcium: 76,
    iron: 1,
    sodium: 0.3,
    potassium: 196,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    name: "Peanuts",
    category: "Nuts",
    servingSize: 28,
    servingUnit: "g",
    calories: 161,
    protein: 7.3,
    carbs: 5.7,
    fat: 14,
    fiber: 2.5,
    calcium: 15,
    iron: 1.3,
    sodium: 2,
    potassium: 189,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    name: "Coconut (Fresh)",
    category: "Nuts",
    servingSize: 100,
    servingUnit: "g",
    calories: 354,
    protein: 3.3,
    carbs: 15,
    fat: 33,
    fiber: 9,
    calcium: 14,
    iron: 2.4,
    sodium: 20,
    potassium: 356,
    vitaminC: 3.3,
    vitaminA: 0,
  },

  // Indian Sweets & Prepared Foods
  {
    name: "Idli",
    category: "Prepared Foods",
    servingSize: 45,
    servingUnit: "piece",
    calories: 39,
    protein: 1.5,
    carbs: 8,
    fat: 0.1,
    fiber: 0.3,
    calcium: 10,
    iron: 0.3,
    sodium: 170,
    potassium: 25,
    vitaminC: 0,
    vitaminA: 0,
    description: "One piece of idli (steamed rice cake)",
  },
  {
    name: "Dosa",
    category: "Prepared Foods",
    servingSize: 100,
    servingUnit: "piece",
    calories: 168,
    protein: 3.5,
    carbs: 28,
    fat: 5,
    fiber: 0.5,
    calcium: 28,
    iron: 1.2,
    sodium: 280,
    potassium: 75,
    vitaminC: 0,
    vitaminA: 50,
  },
  {
    name: "Khichdi",
    category: "Prepared Foods",
    servingSize: 150,
    servingUnit: "bowl",
    calories: 176,
    protein: 5,
    carbs: 30,
    fat: 3,
    fiber: 1.5,
    calcium: 25,
    iron: 1.5,
    sodium: 350,
    potassium: 150,
    vitaminC: 2,
    vitaminA: 25,
  },
];

const extendedIndianFoods = [
  // Breakfast Items
  {
    name: "Poha",
    category: "Breakfast",
    servingSize: 1,
    servingUnit: "plate",
    calories: 260,
    protein: 6,
    carbs: 46,
    fat: 6,
    fiber: 3,
    calcium: 30,
    iron: 2.1,
    sodium: 360,
    potassium: 210,
    vitaminC: 8,
    vitaminA: 180,
    aliases: ["flattened rice", "kanda poha"],
  },
  {
    name: "Upma",
    category: "Breakfast",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 230,
    protein: 6,
    carbs: 38,
    fat: 7,
    fiber: 3,
    calcium: 24,
    iron: 1.7,
    sodium: 410,
    potassium: 160,
    vitaminC: 5,
    vitaminA: 120,
  },
  {
    name: "Masala Dosa",
    category: "Breakfast",
    servingSize: 1,
    servingUnit: "piece",
    calories: 330,
    protein: 7,
    carbs: 52,
    fat: 11,
    fiber: 4,
    calcium: 45,
    iron: 2.2,
    sodium: 520,
    potassium: 360,
    vitaminC: 10,
    vitaminA: 180,
  },
  {
    name: "Uttapam",
    category: "Breakfast",
    servingSize: 1,
    servingUnit: "piece",
    calories: 210,
    protein: 5,
    carbs: 35,
    fat: 6,
    fiber: 2,
    calcium: 35,
    iron: 1.5,
    sodium: 340,
    potassium: 210,
    vitaminC: 8,
    vitaminA: 150,
  },
  {
    name: "Dhokla",
    category: "Breakfast",
    servingSize: 100,
    servingUnit: "g",
    calories: 180,
    protein: 7,
    carbs: 28,
    fat: 4,
    fiber: 2,
    calcium: 28,
    iron: 1.2,
    sodium: 280,
    potassium: 180,
    vitaminC: 3,
    vitaminA: 100,
  },
  {
    name: "Appam",
    category: "Breakfast",
    servingSize: 2,
    servingUnit: "pieces",
    calories: 240,
    protein: 4,
    carbs: 42,
    fat: 5,
    fiber: 1.5,
    calcium: 32,
    iron: 1.3,
    sodium: 200,
    potassium: 140,
    vitaminC: 2,
    vitaminA: 80,
  },

  // Breads
  {
    name: "Paratha (Aloo Paratha)",
    category: "Breads",
    servingSize: 1,
    servingUnit: "piece",
    calories: 280,
    protein: 7,
    carbs: 38,
    fat: 12,
    fiber: 3,
    calcium: 48,
    iron: 2,
    sodium: 480,
    potassium: 280,
    vitaminC: 5,
    vitaminA: 120,
    aliases: ["aloo parantha"],
  },
  {
    name: "Puri (Fried Bread)",
    category: "Breads",
    servingSize: 1,
    servingUnit: "piece",
    calories: 150,
    protein: 3,
    carbs: 16,
    fat: 8,
    fiber: 0.5,
    calcium: 20,
    iron: 1.2,
    sodium: 100,
    potassium: 45,
    vitaminC: 0,
    vitaminA: 30,
  },
  {
    name: "Chapati",
    category: "Breads",
    servingSize: 1,
    servingUnit: "piece",
    calories: 104,
    protein: 3.5,
    carbs: 18,
    fat: 1.2,
    fiber: 3,
    calcium: 35,
    iron: 1.8,
    sodium: 150,
    potassium: 100,
    vitaminC: 0,
    vitaminA: 15,
  },

  // Additional Vegetables
  {
    name: "Carrot",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    calcium: 33,
    iron: 0.3,
    sodium: 69,
    potassium: 320,
    vitaminC: 5.5,
    vitaminA: 8350,
  },
  {
    name: "Cucumber",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.2,
    fiber: 0.5,
    calcium: 16,
    iron: 0.3,
    sodium: 2,
    potassium: 147,
    vitaminC: 2.8,
    vitaminA: 105,
  },
  {
    name: "Beetroot",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 43,
    protein: 1.6,
    carbs: 10,
    fat: 0.2,
    fiber: 2.4,
    calcium: 16,
    iron: 0.8,
    sodium: 78,
    potassium: 325,
    vitaminC: 4.9,
    vitaminA: 20,
  },
  {
    name: "Green Peas",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 81,
    protein: 5.4,
    carbs: 14,
    fat: 0.4,
    fiber: 2.4,
    calcium: 25,
    iron: 1.5,
    sodium: 2,
    potassium: 244,
    vitaminC: 40,
    vitaminA: 540,
  },
  {
    name: "Okra (Bhindi)",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 33,
    protein: 1.9,
    carbs: 7,
    fat: 0.1,
    fiber: 2,
    calcium: 82,
    iron: 0.6,
    sodium: 7,
    potassium: 299,
    vitaminC: 18,
    vitaminA: 375,
    aliases: ["bhindi"],
  },
  {
    name: "Bitter Gourd (Karela)",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 34,
    protein: 1.6,
    carbs: 8,
    fat: 0.2,
    fiber: 2.6,
    calcium: 19,
    iron: 0.4,
    sodium: 5,
    potassium: 296,
    vitaminC: 55,
    vitaminA: 470,
    aliases: ["karela"],
  },
  {
    name: "Pumpkin",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 26,
    protein: 1,
    carbs: 6,
    fat: 0.1,
    fiber: 0.5,
    calcium: 21,
    iron: 0.8,
    sodium: 1,
    potassium: 340,
    vitaminC: 9,
    vitaminA: 3690,
  },
  {
    name: "Bottle Gourd (Lauki)",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 12,
    protein: 0.6,
    carbs: 2.6,
    fat: 0.1,
    fiber: 0.8,
    calcium: 26,
    iron: 0.3,
    sodium: 4,
    potassium: 150,
    vitaminC: 10,
    vitaminA: 40,
    aliases: ["lauki"],
  },
  {
    name: "Radish (Mooli)",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 16,
    protein: 0.7,
    carbs: 3.4,
    fat: 0.1,
    fiber: 1.6,
    calcium: 25,
    iron: 0.3,
    sodium: 39,
    potassium: 233,
    vitaminC: 14.8,
    vitaminA: 7,
  },
  {
    name: "Green Beans",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 31,
    protein: 1.8,
    carbs: 7,
    fat: 0.1,
    fiber: 2.4,
    calcium: 37,
    iron: 0.6,
    sodium: 2,
    potassium: 209,
    vitaminC: 16.3,
    vitaminA: 400,
  },

  // Additional Lentils
  {
    name: "Toor Dal",
    category: "Proteins",
    servingSize: 100,
    servingUnit: "g",
    calories: 120,
    protein: 8.5,
    carbs: 21,
    fat: 0.6,
    fiber: 3.5,
    calcium: 50,
    iron: 2.1,
    sodium: 8,
    potassium: 340,
    vitaminC: 0.5,
    vitaminA: 45,
    aliases: ["arhar dal", "pigeon pea"],
  },
  {
    name: "Masoor Dal",
    category: "Proteins",
    servingSize: 100,
    servingUnit: "g",
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 3.7,
    calcium: 35,
    iron: 3.2,
    sodium: 4,
    potassium: 385,
    vitaminC: 1.2,
    vitaminA: 15,
    aliases: ["red lentil"],
  },
  {
    name: "Urad Dal",
    category: "Proteins",
    servingSize: 100,
    servingUnit: "g",
    calories: 138,
    protein: 10.2,
    carbs: 24,
    fat: 0.8,
    fiber: 4,
    calcium: 138,
    iron: 3.5,
    sodium: 6,
    potassium: 410,
    vitaminC: 0,
    vitaminA: 20,
    aliases: ["black gram"],
  },

  // Curries & Main Dishes
  {
    name: "Sambar",
    category: "Curries",
    servingSize: 1,
    servingUnit: "katori",
    calories: 115,
    protein: 5.5,
    carbs: 17,
    fat: 3,
    fiber: 4.5,
    calcium: 48,
    iron: 1.8,
    sodium: 390,
    potassium: 280,
    vitaminC: 12,
    vitaminA: 420,
  },
  {
    name: "Dal Tadka",
    category: "Curries",
    servingSize: 1,
    servingUnit: "katori",
    calories: 180,
    protein: 9,
    carbs: 24,
    fat: 6,
    fiber: 6,
    calcium: 52,
    iron: 2.4,
    sodium: 430,
    potassium: 320,
    vitaminC: 3,
    vitaminA: 120,
  },
  {
    name: "Chole",
    category: "Curries",
    servingSize: 1,
    servingUnit: "katori",
    calories: 240,
    protein: 10,
    carbs: 34,
    fat: 8,
    fiber: 9,
    calcium: 70,
    iron: 3.1,
    sodium: 480,
    potassium: 420,
    vitaminC: 4,
    vitaminA: 90,
    aliases: ["chana masala"],
  },
  {
    name: "Chicken Curry",
    category: "Curries",
    servingSize: 1,
    servingUnit: "katori",
    calories: 285,
    protein: 24,
    carbs: 8,
    fat: 18,
    fiber: 2,
    calcium: 46,
    iron: 1.6,
    sodium: 520,
    potassium: 390,
    vitaminC: 6,
    vitaminA: 220,
  },
  {
    name: "Paneer Bhurji",
    category: "Curries",
    servingSize: 1,
    servingUnit: "katori",
    calories: 310,
    protein: 18,
    carbs: 9,
    fat: 23,
    fiber: 2,
    calcium: 320,
    iron: 1,
    sodium: 520,
    potassium: 220,
    vitaminC: 8,
    vitaminA: 420,
  },
  {
    name: "Aloo Gobi",
    category: "Curries",
    servingSize: 1,
    servingUnit: "katori",
    calories: 160,
    protein: 4.5,
    carbs: 22,
    fat: 7,
    fiber: 4,
    calcium: 38,
    iron: 1.2,
    sodium: 420,
    potassium: 320,
    vitaminC: 22,
    vitaminA: 180,
  },
  {
    name: "Baingan Bharta",
    category: "Curries",
    servingSize: 1,
    servingUnit: "katori",
    calories: 145,
    protein: 3,
    carbs: 15,
    fat: 8,
    fiber: 3.5,
    calcium: 28,
    iron: 0.8,
    sodium: 380,
    potassium: 310,
    vitaminC: 8,
    vitaminA: 95,
  },
  {
    name: "Rajma (Kidney Beans Curry)",
    category: "Curries",
    servingSize: 1,
    servingUnit: "katori",
    calories: 210,
    protein: 12,
    carbs: 35,
    fat: 2.5,
    fiber: 8,
    calcium: 85,
    iron: 3.2,
    sodium: 360,
    potassium: 420,
    vitaminC: 2,
    vitaminA: 60,
  },
  {
    name: "Chole Bhature",
    category: "Curries",
    servingSize: 1,
    servingUnit: "plate",
    calories: 450,
    protein: 14,
    carbs: 62,
    fat: 16,
    fiber: 8,
    calcium: 95,
    iron: 4,
    sodium: 580,
    potassium: 480,
    vitaminC: 5,
    vitaminA: 150,
  },
  {
    name: "Vegetable Curry",
    category: "Curries",
    servingSize: 1,
    servingUnit: "katori",
    calories: 120,
    protein: 3,
    carbs: 18,
    fat: 4.5,
    fiber: 3.5,
    calcium: 42,
    iron: 1.1,
    sodium: 340,
    potassium: 280,
    vitaminC: 18,
    vitaminA: 380,
  },
  {
    name: "Rasam",
    category: "Curries",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 75,
    protein: 2,
    carbs: 12,
    fat: 2,
    fiber: 1.5,
    calcium: 28,
    iron: 0.9,
    sodium: 380,
    potassium: 210,
    vitaminC: 10,
    vitaminA: 280,
  },

  // Rice & Grain Dishes
  {
    name: "Curd Rice",
    category: "Rice",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 255,
    protein: 8,
    carbs: 42,
    fat: 6,
    fiber: 1.4,
    calcium: 160,
    iron: 0.8,
    sodium: 320,
    potassium: 260,
    vitaminC: 2,
    vitaminA: 140,
  },
  {
    name: "Vegetable Pulao",
    category: "Rice",
    servingSize: 1,
    servingUnit: "plate",
    calories: 340,
    protein: 8,
    carbs: 58,
    fat: 9,
    fiber: 5,
    calcium: 55,
    iron: 2,
    sodium: 540,
    potassium: 330,
    vitaminC: 14,
    vitaminA: 650,
  },
  {
    name: "Lemon Rice",
    category: "Rice",
    servingSize: 1,
    servingUnit: "plate",
    calories: 280,
    protein: 6,
    carbs: 48,
    fat: 7,
    fiber: 2,
    calcium: 28,
    iron: 1.5,
    sodium: 380,
    potassium: 210,
    vitaminC: 12,
    vitaminA: 120,
    aliases: ["nimbu rice"],
  },
  {
    name: "Coconut Rice",
    category: "Rice",
    servingSize: 1,
    servingUnit: "plate",
    calories: 320,
    protein: 6,
    carbs: 50,
    fat: 11,
    fiber: 3,
    calcium: 35,
    iron: 1.6,
    sodium: 340,
    potassium: 240,
    vitaminC: 5,
    vitaminA: 100,
  },
  {
    name: "Tomato Rice",
    category: "Rice",
    servingSize: 1,
    servingUnit: "plate",
    calories: 265,
    protein: 6,
    carbs: 46,
    fat: 6,
    fiber: 2.5,
    calcium: 32,
    iron: 1.4,
    sodium: 360,
    potassium: 280,
    vitaminC: 16,
    vitaminA: 180,
  },
  {
    name: "Biryani (Chicken)",
    category: "Rice",
    servingSize: 1,
    servingUnit: "plate",
    calories: 480,
    protein: 26,
    carbs: 58,
    fat: 16,
    fiber: 2,
    calcium: 52,
    iron: 2.2,
    sodium: 620,
    potassium: 380,
    vitaminC: 8,
    vitaminA: 240,
  },
  {
    name: "Biryani (Vegetable)",
    category: "Rice",
    servingSize: 1,
    servingUnit: "plate",
    calories: 380,
    protein: 10,
    carbs: 62,
    fat: 11,
    fiber: 4,
    calcium: 58,
    iron: 2.5,
    sodium: 540,
    potassium: 350,
    vitaminC: 12,
    vitaminA: 520,
  },
  {
    name: "Idiyappam",
    category: "Rice",
    servingSize: 1,
    servingUnit: "plate",
    calories: 220,
    protein: 5,
    carbs: 42,
    fat: 3,
    fiber: 1,
    calcium: 25,
    iron: 1.1,
    sodium: 280,
    potassium: 140,
    vitaminC: 2,
    vitaminA: 80,
  },

  // Beverages
  {
    name: "Tea With Milk And Sugar",
    category: "Beverages",
    servingSize: 1,
    servingUnit: "cup",
    calories: 90,
    protein: 2.5,
    carbs: 13,
    fat: 3,
    fiber: 0,
    calcium: 95,
    iron: 0.1,
    sodium: 42,
    potassium: 120,
    vitaminC: 0,
    vitaminA: 90,
    aliases: ["chai", "milk tea"],
  },
  {
    name: "Buttermilk",
    category: "Beverages",
    servingSize: 1,
    servingUnit: "glass",
    calories: 55,
    protein: 3,
    carbs: 6,
    fat: 2,
    fiber: 0,
    calcium: 140,
    iron: 0.1,
    sodium: 180,
    potassium: 180,
    vitaminC: 1,
    vitaminA: 90,
    aliases: ["chaas", "mattha"],
  },
  {
    name: "Lassi (Sweet)",
    category: "Beverages",
    servingSize: 250,
    servingUnit: "ml",
    calories: 180,
    protein: 5,
    carbs: 26,
    fat: 5,
    fiber: 0,
    calcium: 200,
    iron: 0.1,
    sodium: 85,
    potassium: 210,
    vitaminC: 0.5,
    vitaminA: 120,
  },
  {
    name: "Masala Tea (Masala Chai)",
    category: "Beverages",
    servingSize: 1,
    servingUnit: "cup",
    calories: 110,
    protein: 3,
    carbs: 16,
    fat: 3.5,
    fiber: 0,
    calcium: 100,
    iron: 0.2,
    sodium: 55,
    potassium: 140,
    vitaminC: 0.5,
    vitaminA: 100,
  },
  {
    name: "Coffee",
    category: "Beverages",
    servingSize: 1,
    servingUnit: "cup",
    calories: 80,
    protein: 2,
    carbs: 11,
    fat: 2.5,
    fiber: 0,
    calcium: 80,
    iron: 0.1,
    sodium: 35,
    potassium: 95,
    vitaminC: 0,
    vitaminA: 70,
  },
  {
    name: "Lemon Water",
    category: "Beverages",
    servingSize: 1,
    servingUnit: "glass",
    calories: 10,
    protein: 0.2,
    carbs: 3,
    fat: 0,
    fiber: 0.3,
    calcium: 6,
    iron: 0.1,
    sodium: 1,
    potassium: 60,
    vitaminC: 20,
    vitaminA: 5,
  },

  // Snacks & Street Foods
  {
    name: "Samosa",
    category: "Snacks",
    servingSize: 1,
    servingUnit: "piece",
    calories: 260,
    protein: 5,
    carbs: 32,
    fat: 13,
    fiber: 3,
    calcium: 24,
    iron: 1.6,
    sodium: 410,
    potassium: 210,
    vitaminC: 4,
    vitaminA: 70,
  },
  {
    name: "Roasted Chana",
    category: "Snacks",
    servingSize: 50,
    servingUnit: "g",
    calories: 190,
    protein: 10,
    carbs: 31,
    fat: 3,
    fiber: 9,
    calcium: 45,
    iron: 2.5,
    sodium: 18,
    potassium: 360,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    name: "Pakora",
    category: "Snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 320,
    protein: 6,
    carbs: 28,
    fat: 21,
    fiber: 2,
    calcium: 32,
    iron: 1.4,
    sodium: 480,
    potassium: 280,
    vitaminC: 8,
    vitaminA: 200,
  },
  {
    name: "Bhajiya",
    category: "Snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 310,
    protein: 5,
    carbs: 30,
    fat: 18,
    fiber: 2.5,
    calcium: 28,
    iron: 1.2,
    sodium: 420,
    potassium: 240,
    vitaminC: 6,
    vitaminA: 180,
  },
  {
    name: "Kachumber Salad",
    category: "Snacks",
    servingSize: 150,
    servingUnit: "bowl",
    calories: 75,
    protein: 1.5,
    carbs: 14,
    fat: 1,
    fiber: 3,
    calcium: 28,
    iron: 0.5,
    sodium: 80,
    potassium: 320,
    vitaminC: 24,
    vitaminA: 420,
  },
  {
    name: "Vegetable Salad",
    category: "Snacks",
    servingSize: 200,
    servingUnit: "bowl",
    calories: 95,
    protein: 3,
    carbs: 16,
    fat: 2,
    fiber: 4,
    calcium: 45,
    iron: 1,
    sodium: 60,
    potassium: 410,
    vitaminC: 35,
    vitaminA: 580,
  },
  {
    name: "Bhel Puri",
    category: "Snacks",
    servingSize: 100,
    servingUnit: "g",
    calories: 280,
    protein: 6,
    carbs: 42,
    fat: 10,
    fiber: 3,
    calcium: 35,
    iron: 1.6,
    sodium: 520,
    potassium: 280,
    vitaminC: 12,
    vitaminA: 140,
  },
  {
    name: "Popcorn",
    category: "Snacks",
    servingSize: 30,
    servingUnit: "g",
    calories: 120,
    protein: 4,
    carbs: 22,
    fat: 1.5,
    fiber: 4.2,
    calcium: 4,
    iron: 0.6,
    sodium: 190,
    potassium: 120,
    vitaminC: 0,
    vitaminA: 40,
  },

  // Condiments & Oils
  {
    name: "Coconut Oil",
    category: "Oils",
    servingSize: 14,
    servingUnit: "g",
    calories: 120,
    protein: 0,
    carbs: 0,
    fat: 13.5,
    fiber: 0,
    calcium: 0,
    iron: 0,
    sodium: 0,
    potassium: 0,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    name: "Mustard Oil",
    category: "Oils",
    servingSize: 14,
    servingUnit: "g",
    calories: 120,
    protein: 0,
    carbs: 0,
    fat: 13.6,
    fiber: 0,
    calcium: 0,
    iron: 0,
    sodium: 0,
    potassium: 0,
    vitaminC: 0,
    vitaminA: 0,
  },
  {
    name: "Sesame Oil",
    category: "Oils",
    servingSize: 14,
    servingUnit: "g",
    calories: 120,
    protein: 0,
    carbs: 0,
    fat: 13.6,
    fiber: 0,
    calcium: 0,
    iron: 0,
    sodium: 0,
    potassium: 0,
    vitaminC: 0,
    vitaminA: 0,
  },

  // Additional Fruits
  {
    name: "Apple",
    category: "Fruits",
    servingSize: 182,
    servingUnit: "piece",
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
    fiber: 4.4,
    calcium: 11,
    iron: 0.2,
    sodium: 2,
    potassium: 195,
    vitaminC: 5.7,
    vitaminA: 54,
  },
  {
    name: "Grapes",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 67,
    protein: 0.7,
    carbs: 17,
    fat: 0.4,
    fiber: 0.9,
    calcium: 14,
    iron: 0.4,
    sodium: 2,
    potassium: 191,
    vitaminC: 3.2,
    vitaminA: 66,
  },
  {
    name: "Pomegranate",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 83,
    protein: 1.7,
    carbs: 19,
    fat: 1.2,
    fiber: 4,
    calcium: 10,
    iron: 0.3,
    sodium: 3,
    potassium: 236,
    vitaminC: 10.2,
    vitaminA: 16,
  },
  {
    name: "Pineapple",
    category: "Fruits",
    servingSize: 165,
    servingUnit: "g",
    calories: 82,
    protein: 0.9,
    carbs: 22,
    fat: 0.2,
    fiber: 2.3,
    calcium: 21,
    iron: 0.3,
    sodium: 2,
    potassium: 180,
    vitaminC: 47,
    vitaminA: 35,
  },
  {
    name: "Strawberry",
    category: "Fruits",
    servingSize: 152,
    servingUnit: "cup",
    calories: 49,
    protein: 1,
    carbs: 12,
    fat: 0.5,
    fiber: 3,
    calcium: 27,
    iron: 0.4,
    sodium: 2,
    potassium: 254,
    vitaminC: 97,
    vitaminA: 27,
  },

  // More Protein/Nuts
  {
    name: "Cashew Nuts",
    category: "Nuts",
    servingSize: 28,
    servingUnit: "g",
    calories: 157,
    protein: 5.2,
    carbs: 9,
    fat: 12,
    fiber: 0.9,
    calcium: 37,
    iron: 1.9,
    sodium: 12,
    potassium: 168,
    vitaminC: 0.3,
    vitaminA: 0,
  },
  {
    name: "Walnuts",
    category: "Nuts",
    servingSize: 28,
    servingUnit: "g",
    calories: 185,
    protein: 4.3,
    carbs: 4,
    fat: 18.5,
    fiber: 1.9,
    calcium: 42,
    iron: 0.8,
    sodium: 2,
    potassium: 202,
    vitaminC: 1.3,
    vitaminA: 20,
  },
  {
    name: "Sunflower Seeds",
    category: "Nuts",
    servingSize: 28,
    servingUnit: "g",
    calories: 165,
    protein: 5.5,
    carbs: 7,
    fat: 14,
    fiber: 2.4,
    calcium: 78,
    iron: 1.5,
    sodium: 60,
    potassium: 210,
    vitaminC: 1.5,
    vitaminA: 42,
  },
];

const roundNutrition = (value) => Math.round(value * 10) / 10;

const maharashtrianNutritionProfiles = {
  breakfast: {
    proteinRatio: 0.1,
    carbsRatio: 0.66,
    fatRatio: 0.24,
    fiber: 1,
    calcium: 12,
    iron: 0.55,
    sodium: 150,
    potassium: 90,
    vitaminC: 3,
    vitaminA: 50,
  },
  streetFood: {
    proteinRatio: 0.09,
    carbsRatio: 0.52,
    fatRatio: 0.39,
    fiber: 0.8,
    calcium: 12,
    iron: 0.5,
    sodium: 190,
    potassium: 100,
    vitaminC: 2.5,
    vitaminA: 45,
  },
  friedSnack: {
    proteinRatio: 0.08,
    carbsRatio: 0.45,
    fatRatio: 0.47,
    fiber: 0.7,
    calcium: 10,
    iron: 0.45,
    sodium: 180,
    potassium: 85,
    vitaminC: 2,
    vitaminA: 35,
  },
  bhakri: {
    proteinRatio: 0.12,
    carbsRatio: 0.76,
    fatRatio: 0.12,
    fiber: 1.6,
    calcium: 16,
    iron: 0.75,
    sodium: 65,
    potassium: 110,
    vitaminC: 0.2,
    vitaminA: 5,
  },
  dalCurry: {
    proteinRatio: 0.18,
    carbsRatio: 0.52,
    fatRatio: 0.3,
    fiber: 1.8,
    calcium: 18,
    iron: 0.8,
    sodium: 140,
    potassium: 140,
    vitaminC: 2,
    vitaminA: 35,
  },
  vegCurry: {
    proteinRatio: 0.11,
    carbsRatio: 0.4,
    fatRatio: 0.49,
    fiber: 1.6,
    calcium: 15,
    iron: 0.55,
    sodium: 160,
    potassium: 140,
    vitaminC: 4,
    vitaminA: 80,
  },
  salad: {
    proteinRatio: 0.12,
    carbsRatio: 0.72,
    fatRatio: 0.16,
    fiber: 2.1,
    calcium: 18,
    iron: 0.35,
    sodium: 18,
    potassium: 170,
    vitaminC: 12,
    vitaminA: 85,
  },
  soup: {
    proteinRatio: 0.1,
    carbsRatio: 0.54,
    fatRatio: 0.36,
    fiber: 0.9,
    calcium: 12,
    iron: 0.35,
    sodium: 135,
    potassium: 115,
    vitaminC: 8,
    vitaminA: 45,
  },
  riceDish: {
    proteinRatio: 0.08,
    carbsRatio: 0.72,
    fatRatio: 0.2,
    fiber: 0.7,
    calcium: 9,
    iron: 0.35,
    sodium: 125,
    potassium: 75,
    vitaminC: 1.5,
    vitaminA: 25,
  },
  beverage: {
    proteinRatio: 0.06,
    carbsRatio: 0.36,
    fatRatio: 0.58,
    fiber: 0.2,
    calcium: 25,
    iron: 0.2,
    sodium: 75,
    potassium: 90,
    vitaminC: 2,
    vitaminA: 30,
  },
  dairy: {
    proteinRatio: 0.16,
    carbsRatio: 0.24,
    fatRatio: 0.6,
    fiber: 0,
    calcium: 95,
    iron: 0.08,
    sodium: 45,
    potassium: 95,
    vitaminC: 0.4,
    vitaminA: 70,
  },
  fatOnly: {
    proteinRatio: 0,
    carbsRatio: 0,
    fatRatio: 1,
    fiber: 0,
    calcium: 2,
    iron: 0,
    sodium: 1,
    potassium: 1,
    vitaminC: 0,
    vitaminA: 120,
  },
  fruit: {
    proteinRatio: 0.04,
    carbsRatio: 0.92,
    fatRatio: 0.04,
    fiber: 2.2,
    calcium: 12,
    iron: 0.22,
    sodium: 2,
    potassium: 150,
    vitaminC: 28,
    vitaminA: 80,
  },
  nutsSnack: {
    proteinRatio: 0.14,
    carbsRatio: 0.28,
    fatRatio: 0.58,
    fiber: 2,
    calcium: 18,
    iron: 0.7,
    sodium: 25,
    potassium: 140,
    vitaminC: 0.2,
    vitaminA: 5,
  },
  egg: {
    proteinRatio: 0.34,
    carbsRatio: 0.04,
    fatRatio: 0.62,
    fiber: 0,
    calcium: 28,
    iron: 0.8,
    sodium: 90,
    potassium: 95,
    vitaminC: 0,
    vitaminA: 160,
  },
  fish: {
    proteinRatio: 0.32,
    carbsRatio: 0.08,
    fatRatio: 0.6,
    fiber: 0.2,
    calcium: 18,
    iron: 0.45,
    sodium: 120,
    potassium: 145,
    vitaminC: 1,
    vitaminA: 20,
  },
  meat: {
    proteinRatio: 0.3,
    carbsRatio: 0.08,
    fatRatio: 0.62,
    fiber: 0.2,
    calcium: 12,
    iron: 0.55,
    sodium: 125,
    potassium: 130,
    vitaminC: 1,
    vitaminA: 25,
  },
  sweet: {
    proteinRatio: 0.08,
    carbsRatio: 0.58,
    fatRatio: 0.34,
    fiber: 0.6,
    calcium: 20,
    iron: 0.35,
    sodium: 55,
    potassium: 65,
    vitaminC: 0.4,
    vitaminA: 35,
  },
  fasting: {
    proteinRatio: 0.09,
    carbsRatio: 0.6,
    fatRatio: 0.31,
    fiber: 1,
    calcium: 16,
    iron: 0.45,
    sodium: 95,
    potassium: 120,
    vitaminC: 2,
    vitaminA: 40,
  },
  thali: {
    proteinRatio: 0.13,
    carbsRatio: 0.58,
    fatRatio: 0.29,
    fiber: 1.2,
    calcium: 14,
    iron: 0.55,
    sodium: 135,
    potassium: 115,
    vitaminC: 2,
    vitaminA: 45,
  },
};

const estimateNutrition = (calories, profileKey) => {
  const profile = maharashtrianNutritionProfiles[profileKey];

  return {
    protein: roundNutrition((calories * profile.proteinRatio) / 4),
    carbs: roundNutrition((calories * profile.carbsRatio) / 4),
    fat: roundNutrition((calories * profile.fatRatio) / 9),
    fiber: roundNutrition((calories / 100) * profile.fiber),
    calcium: roundNutrition((calories / 100) * profile.calcium),
    iron: roundNutrition((calories / 100) * profile.iron),
    sodium: roundNutrition((calories / 100) * profile.sodium),
    potassium: roundNutrition((calories / 100) * profile.potassium),
    vitaminC: roundNutrition((calories / 100) * profile.vitaminC),
    vitaminA: roundNutrition((calories / 100) * profile.vitaminA),
  };
};

const maharashtrianFood = ({
  name,
  category,
  servingSize = 1,
  servingUnit,
  calories,
  range,
  profile,
  serving,
  aliases,
  note,
}) => ({
  name,
  category,
  servingSize,
  servingUnit,
  calories,
  ...estimateNutrition(calories, profile),
  description: [
    note,
    serving ? `Serving: ${serving}.` : null,
    `Approximate calories from supplied Maharashtrian chart: ${range}.`,
    "Macros and micronutrients are estimated because the supplied chart only included calories.",
  ]
    .filter(Boolean)
    .join(" "),
  ...(aliases?.length ? { aliases } : {}),
});

const maharashtrianFoods = [
  // Maharashtrian Breakfast Foods
  maharashtrianFood({
    name: "Kanda Poha",
    category: "Maharashtrian Breakfast",
    servingUnit: "plate",
    calories: 300,
    range: "250-350 kcal",
    profile: "breakfast",
    aliases: ["onion poha", "kande pohe"],
  }),
  maharashtrianFood({
    name: "Batata Poha",
    category: "Maharashtrian Breakfast",
    servingUnit: "plate",
    calories: 350,
    range: "300-400 kcal",
    profile: "breakfast",
    aliases: ["potato poha"],
  }),
  maharashtrianFood({
    name: "Dadpe Pohe",
    category: "Maharashtrian Breakfast",
    servingUnit: "plate",
    calories: 260,
    range: "220-300 kcal",
    profile: "breakfast",
    aliases: ["dadpe poha"],
  }),
  maharashtrianFood({
    name: "Indori Poha",
    category: "Maharashtrian Breakfast",
    servingUnit: "plate",
    calories: 350,
    range: "300-400 kcal",
    profile: "breakfast",
    note: "Popular in Maharashtra.",
  }),
  maharashtrianFood({
    name: "Upma",
    category: "Maharashtrian Breakfast",
    servingUnit: "bowl",
    calories: 260,
    range: "220-300 kcal",
    profile: "breakfast",
  }),
  maharashtrianFood({
    name: "Sabudana Khichdi",
    category: "Maharashtrian Breakfast",
    servingUnit: "bowl",
    calories: 400,
    range: "350-450 kcal",
    profile: "fasting",
    aliases: ["sago khichdi", "upvas khichdi"],
  }),
  maharashtrianFood({
    name: "Sabudana Thalipeeth",
    category: "Maharashtrian Breakfast",
    servingUnit: "piece",
    calories: 300,
    range: "250-350 kcal",
    profile: "fasting",
    aliases: ["sago thalipeeth"],
  }),
  maharashtrianFood({
    name: "Ghavan",
    category: "Maharashtrian Breakfast",
    servingUnit: "serving",
    calories: 250,
    range: "200-300 kcal",
    profile: "breakfast",
    serving: "2 pieces",
  }),
  maharashtrianFood({
    name: "Amboli",
    category: "Maharashtrian Breakfast",
    servingUnit: "serving",
    calories: 215,
    range: "180-250 kcal",
    profile: "breakfast",
    serving: "2 pieces",
  }),
  maharashtrianFood({
    name: "Thalipeeth",
    category: "Maharashtrian Breakfast",
    servingUnit: "piece",
    calories: 300,
    range: "250-350 kcal",
    profile: "breakfast",
    serving: "1 medium piece",
  }),
  maharashtrianFood({
    name: "Kanda Thalipeeth",
    category: "Maharashtrian Breakfast",
    servingUnit: "piece",
    calories: 330,
    range: "280-380 kcal",
    profile: "breakfast",
    serving: "1 medium piece",
    aliases: ["onion thalipeeth"],
  }),
  maharashtrianFood({
    name: "Varan Bhaat",
    category: "Maharashtrian Main Course",
    servingUnit: "plate",
    calories: 550,
    range: "500-600 kcal",
    profile: "riceDish",
    aliases: ["varan bhat", "dal rice"],
  }),
  maharashtrianFood({
    name: "Mug Varan",
    category: "Maharashtrian Main Course",
    servingUnit: "bowl",
    calories: 165,
    range: "150-180 kcal",
    profile: "dalCurry",
    aliases: ["moong varan", "moong dal varan"],
  }),
  maharashtrianFood({
    name: "Ukad",
    category: "Maharashtrian Breakfast",
    servingUnit: "serving",
    calories: 215,
    range: "180-250 kcal",
    profile: "breakfast",
  }),
  maharashtrianFood({
    name: "Tandlachi Bhakri",
    category: "Bhakri & Roti",
    servingUnit: "piece",
    calories: 150,
    range: "120-180 kcal",
    profile: "bhakri",
    serving: "1 bhakri",
    aliases: ["rice bhakri", "tandalachi bhakri"],
  }),

  // Famous Maharashtrian Street Foods
  maharashtrianFood({
    name: "Vada Pav",
    category: "Maharashtrian Street Food",
    servingUnit: "piece",
    calories: 315,
    range: "280-350 kcal",
    profile: "streetFood",
  }),
  maharashtrianFood({
    name: "Misal Pav",
    category: "Maharashtrian Street Food",
    servingUnit: "plate",
    calories: 400,
    range: "350-450 kcal",
    profile: "streetFood",
  }),
  maharashtrianFood({
    name: "Dahi Misal",
    category: "Maharashtrian Street Food",
    servingUnit: "plate",
    calories: 325,
    range: "300-350 kcal",
    profile: "streetFood",
  }),
  maharashtrianFood({
    name: "Pav Bhaji",
    category: "Maharashtrian Street Food",
    servingUnit: "plate",
    calories: 525,
    range: "450-600 kcal",
    profile: "streetFood",
  }),
  maharashtrianFood({
    name: "Bhel Puri",
    category: "Maharashtrian Street Food",
    servingUnit: "plate",
    calories: 300,
    range: "250-350 kcal",
    profile: "streetFood",
  }),
  maharashtrianFood({
    name: "Sev Puri",
    category: "Maharashtrian Street Food",
    servingUnit: "plate",
    calories: 300,
    range: "250-350 kcal",
    profile: "streetFood",
  }),
  maharashtrianFood({
    name: "Pani Puri",
    category: "Maharashtrian Street Food",
    servingUnit: "serving",
    calories: 240,
    range: "180-300 kcal",
    profile: "streetFood",
    serving: "6 pieces",
    aliases: ["golgappa", "puchka"],
  }),
  maharashtrianFood({
    name: "Ragda Pattice",
    category: "Maharashtrian Street Food",
    servingUnit: "plate",
    calories: 425,
    range: "350-500 kcal",
    profile: "streetFood",
    aliases: ["ragda patties"],
  }),
  maharashtrianFood({
    name: "Dabeli",
    category: "Maharashtrian Street Food",
    servingUnit: "piece",
    calories: 300,
    range: "250-350 kcal",
    profile: "streetFood",
  }),
  maharashtrianFood({
    name: "Frankie",
    category: "Maharashtrian Street Food",
    servingUnit: "serving",
    calories: 425,
    range: "350-500 kcal",
    profile: "streetFood",
    serving: "1 roll",
  }),
  maharashtrianFood({
    name: "Kanda Bhaji",
    category: "Maharashtrian Street Food",
    servingSize: 100,
    servingUnit: "g",
    calories: 375,
    range: "300-450 kcal",
    profile: "friedSnack",
    aliases: ["onion bhaji", "onion pakora"],
  }),
  maharashtrianFood({
    name: "Bhaji Pav",
    category: "Maharashtrian Street Food",
    servingUnit: "plate",
    calories: 525,
    range: "450-600 kcal",
    profile: "streetFood",
  }),

  // Bhakri & Roti Varieties
  maharashtrianFood({
    name: "Jowar Bhakri",
    category: "Bhakri & Roti",
    servingUnit: "piece",
    calories: 135,
    range: "120-150 kcal",
    profile: "bhakri",
    serving: "1 medium piece",
    aliases: ["jwari bhakri", "sorghum bhakri"],
  }),
  maharashtrianFood({
    name: "Bajra Bhakri",
    category: "Bhakri & Roti",
    servingUnit: "piece",
    calories: 175,
    range: "150-200 kcal",
    profile: "bhakri",
    serving: "1 medium piece",
    aliases: ["pearl millet bhakri"],
  }),
  maharashtrianFood({
    name: "Nachni Bhakri",
    category: "Bhakri & Roti",
    servingUnit: "piece",
    calories: 155,
    range: "130-180 kcal",
    profile: "bhakri",
    serving: "1 medium piece",
    aliases: ["ragi bhakri", "finger millet bhakri"],
  }),
  maharashtrianFood({
    name: "Rice Bhakri",
    category: "Bhakri & Roti",
    servingUnit: "piece",
    calories: 145,
    range: "120-170 kcal",
    profile: "bhakri",
    serving: "1 medium piece",
    aliases: ["tandlachi bhakri"],
  }),
  maharashtrianFood({
    name: "Wheat Chapati",
    category: "Bhakri & Roti",
    servingUnit: "piece",
    calories: 110,
    range: "100-120 kcal",
    profile: "bhakri",
    aliases: ["chapati", "roti"],
  }),
  maharashtrianFood({
    name: "Multigrain Bhakri",
    category: "Bhakri & Roti",
    servingUnit: "piece",
    calories: 185,
    range: "150-220 kcal",
    profile: "bhakri",
    serving: "1 medium piece",
  }),
  maharashtrianFood({
    name: "Makai Bhakri",
    category: "Bhakri & Roti",
    servingUnit: "piece",
    calories: 155,
    range: "130-180 kcal",
    profile: "bhakri",
    serving: "1 medium piece",
    aliases: ["corn bhakri", "maize bhakri"],
  }),

  // Traditional Maharashtrian Main Course
  maharashtrianFood({
    name: "Pithla",
    category: "Maharashtrian Main Course",
    servingUnit: "bowl",
    calories: 215,
    range: "180-250 kcal",
    profile: "dalCurry",
    aliases: ["pithale"],
  }),
  maharashtrianFood({
    name: "Zunka",
    category: "Maharashtrian Main Course",
    servingUnit: "bowl",
    calories: 215,
    range: "180-250 kcal",
    profile: "dalCurry",
    aliases: ["jhunka"],
  }),
  maharashtrianFood({
    name: "Bharli Vangi",
    category: "Maharashtrian Main Course",
    servingUnit: "bowl",
    calories: 240,
    range: "180-300 kcal",
    profile: "vegCurry",
    aliases: ["stuffed brinjal", "bharli vangi bhaji"],
  }),
  maharashtrianFood({
    name: "Matki Usal",
    category: "Maharashtrian Main Course",
    servingUnit: "bowl",
    calories: 230,
    range: "180-280 kcal",
    profile: "dalCurry",
    aliases: ["moth bean usal"],
  }),
  maharashtrianFood({
    name: "Usal Pav",
    category: "Maharashtrian Main Course",
    servingUnit: "plate",
    calories: 425,
    range: "350-500 kcal",
    profile: "streetFood",
  }),
  maharashtrianFood({
    name: "Amti",
    category: "Maharashtrian Main Course",
    servingUnit: "bowl",
    calories: 150,
    range: "120-180 kcal",
    profile: "dalCurry",
  }),
  maharashtrianFood({
    name: "Katachi Amti",
    category: "Maharashtrian Main Course",
    servingUnit: "bowl",
    calories: 160,
    range: "120-200 kcal",
    profile: "dalCurry",
  }),
  maharashtrianFood({
    name: "Sev Bhaji",
    category: "Maharashtrian Main Course",
    servingUnit: "bowl",
    calories: 300,
    range: "250-350 kcal",
    profile: "vegCurry",
  }),
  maharashtrianFood({
    name: "Kadhi Gole",
    category: "Maharashtrian Main Course",
    servingUnit: "bowl",
    calories: 175,
    range: "150-200 kcal",
    profile: "dalCurry",
    aliases: ["kadhi gole", "kadhi gatte"],
  }),
  maharashtrianFood({
    name: "Masale Bhaat",
    category: "Maharashtrian Main Course",
    servingUnit: "plate",
    calories: 475,
    range: "450-500 kcal",
    profile: "riceDish",
    aliases: ["masala bhaat"],
  }),
  maharashtrianFood({
    name: "Vangi Bhaat",
    category: "Maharashtrian Main Course",
    servingUnit: "plate",
    calories: 400,
    range: "350-450 kcal",
    profile: "riceDish",
    aliases: ["brinjal rice"],
  }),
  maharashtrianFood({
    name: "Khichdi",
    category: "Maharashtrian Main Course",
    servingUnit: "bowl",
    calories: 300,
    range: "250-350 kcal",
    profile: "riceDish",
  }),
  maharashtrianFood({
    name: "Dahi Bhaat",
    category: "Maharashtrian Main Course",
    servingUnit: "bowl",
    calories: 300,
    range: "250-350 kcal",
    profile: "riceDish",
    aliases: ["curd rice", "dahi bhat"],
  }),
  maharashtrianFood({
    name: "Phodnicha Bhaat",
    category: "Maharashtrian Main Course",
    servingUnit: "bowl",
    calories: 300,
    range: "250-350 kcal",
    profile: "riceDish",
    aliases: ["fodnicha bhat", "tempered rice"],
  }),

  // Konkan Special Foods
  maharashtrianFood({
    name: "Sol Kadhi",
    category: "Konkan Special",
    servingUnit: "glass",
    calories: 115,
    range: "80-150 kcal",
    profile: "beverage",
    aliases: ["solkadhi"],
  }),
  maharashtrianFood({
    name: "Kombdi Vade",
    category: "Konkan Special",
    servingUnit: "plate",
    calories: 750,
    range: "600-900 kcal",
    profile: "meat",
    aliases: ["kombdi vade", "chicken vade"],
  }),
  maharashtrianFood({
    name: "Malvani Fish Curry",
    category: "Konkan Special",
    servingUnit: "bowl",
    calories: 325,
    range: "250-400 kcal",
    profile: "fish",
  }),
  maharashtrianFood({
    name: "Bombil Fry",
    category: "Konkan Special",
    servingSize: 100,
    servingUnit: "g",
    calories: 300,
    range: "250-350 kcal",
    profile: "fish",
    aliases: ["bombay duck fry"],
  }),
  maharashtrianFood({
    name: "Surmai Fry",
    category: "Konkan Special",
    servingSize: 100,
    servingUnit: "g",
    calories: 325,
    range: "250-400 kcal",
    profile: "fish",
    aliases: ["seer fish fry"],
  }),
  maharashtrianFood({
    name: "Bangda Curry",
    category: "Konkan Special",
    servingUnit: "bowl",
    calories: 325,
    range: "250-400 kcal",
    profile: "fish",
    aliases: ["mackerel curry"],
  }),
  maharashtrianFood({
    name: "Kolambi Curry",
    category: "Konkan Special",
    servingUnit: "bowl",
    calories: 350,
    range: "250-450 kcal",
    profile: "fish",
    aliases: ["prawn curry", "shrimp curry"],
  }),
  maharashtrianFood({
    name: "Fish Koliwada",
    category: "Konkan Special",
    servingSize: 100,
    servingUnit: "g",
    calories: 375,
    range: "300-450 kcal",
    profile: "fish",
  }),

  // Kolhapuri Foods
  maharashtrianFood({
    name: "Kolhapuri Misal",
    category: "Kolhapuri Foods",
    servingUnit: "plate",
    calories: 475,
    range: "400-550 kcal",
    profile: "streetFood",
  }),
  maharashtrianFood({
    name: "Tambda Rassa",
    category: "Kolhapuri Foods",
    servingUnit: "bowl",
    calories: 185,
    range: "120-250 kcal",
    profile: "meat",
    aliases: ["tambda rassa"],
  }),
  maharashtrianFood({
    name: "Pandhra Rassa",
    category: "Kolhapuri Foods",
    servingUnit: "bowl",
    calories: 225,
    range: "150-300 kcal",
    profile: "meat",
  }),
  maharashtrianFood({
    name: "Mutton Sukka",
    category: "Kolhapuri Foods",
    servingSize: 100,
    servingUnit: "g",
    calories: 375,
    range: "300-450 kcal",
    profile: "meat",
    aliases: ["mutton sukha"],
  }),
  maharashtrianFood({
    name: "Kolhapuri Chicken",
    category: "Kolhapuri Foods",
    servingUnit: "bowl",
    calories: 400,
    range: "300-500 kcal",
    profile: "meat",
  }),
  maharashtrianFood({
    name: "Mutton Thali",
    category: "Kolhapuri Foods",
    servingUnit: "plate",
    calories: 1000,
    range: "800-1200 kcal",
    profile: "thali",
  }),

  // Maharashtrian Sweets
  maharashtrianFood({
    name: "Ukdiche Modak",
    category: "Maharashtrian Sweets",
    servingUnit: "piece",
    calories: 150,
    range: "120-180 kcal",
    profile: "sweet",
    aliases: ["steamed modak"],
  }),
  maharashtrianFood({
    name: "Fried Modak",
    category: "Maharashtrian Sweets",
    servingUnit: "piece",
    calories: 215,
    range: "180-250 kcal",
    profile: "sweet",
  }),
  maharashtrianFood({
    name: "Puran Poli",
    category: "Maharashtrian Sweets",
    servingUnit: "piece",
    calories: 300,
    range: "250-350 kcal",
    profile: "sweet",
    aliases: ["puranpoli"],
  }),
  maharashtrianFood({
    name: "Shrikhand",
    category: "Maharashtrian Sweets",
    servingSize: 100,
    servingUnit: "g",
    calories: 300,
    range: "250-350 kcal",
    profile: "sweet",
  }),
  maharashtrianFood({
    name: "Amrakhand",
    category: "Maharashtrian Sweets",
    servingSize: 100,
    servingUnit: "g",
    calories: 300,
    range: "250-350 kcal",
    profile: "sweet",
    aliases: ["mango shrikhand"],
  }),
  maharashtrianFood({
    name: "Basundi",
    category: "Maharashtrian Sweets",
    servingUnit: "bowl",
    calories: 325,
    range: "250-400 kcal",
    profile: "sweet",
  }),
  maharashtrianFood({
    name: "Sheera",
    category: "Maharashtrian Sweets",
    servingUnit: "bowl",
    calories: 375,
    range: "300-450 kcal",
    profile: "sweet",
    aliases: ["sooji halwa"],
  }),
  maharashtrianFood({
    name: "Rava Ladoo",
    category: "Maharashtrian Sweets",
    servingUnit: "piece",
    calories: 150,
    range: "120-180 kcal",
    profile: "sweet",
    aliases: ["rava laddu"],
  }),
  maharashtrianFood({
    name: "Besan Ladoo",
    category: "Maharashtrian Sweets",
    servingUnit: "piece",
    calories: 185,
    range: "150-220 kcal",
    profile: "sweet",
    aliases: ["besan laddu"],
  }),
  maharashtrianFood({
    name: "Anarsa",
    category: "Maharashtrian Sweets",
    servingUnit: "piece",
    calories: 150,
    range: "120-180 kcal",
    profile: "sweet",
  }),
  maharashtrianFood({
    name: "Karanji",
    category: "Maharashtrian Sweets",
    servingUnit: "piece",
    calories: 215,
    range: "180-250 kcal",
    profile: "sweet",
  }),
  maharashtrianFood({
    name: "Chirote",
    category: "Maharashtrian Sweets",
    servingUnit: "piece",
    calories: 200,
    range: "150-250 kcal",
    profile: "sweet",
  }),
  maharashtrianFood({
    name: "Gul Poli",
    category: "Maharashtrian Sweets",
    servingUnit: "piece",
    calories: 300,
    range: "250-350 kcal",
    profile: "sweet",
  }),
  maharashtrianFood({
    name: "Tilgul Ladoo",
    category: "Maharashtrian Sweets",
    servingUnit: "piece",
    calories: 115,
    range: "80-150 kcal",
    profile: "sweet",
    aliases: ["tilgul laddu", "til ladoo"],
  }),

  // Fasting (Upvas) Foods
  maharashtrianFood({
    name: "Sabudana Vada",
    category: "Fasting Foods",
    servingUnit: "piece",
    calories: 200,
    range: "150-250 kcal",
    profile: "fasting",
    aliases: ["sago vada"],
  }),
  maharashtrianFood({
    name: "Rajgira Puri",
    category: "Fasting Foods",
    servingUnit: "serving",
    calories: 300,
    range: "250-350 kcal",
    profile: "fasting",
    serving: "2 pieces",
  }),
  maharashtrianFood({
    name: "Rajgira Thalipeeth",
    category: "Fasting Foods",
    servingUnit: "piece",
    calories: 250,
    range: "200-300 kcal",
    profile: "fasting",
  }),
  maharashtrianFood({
    name: "Shengdana Amti",
    category: "Fasting Foods",
    servingUnit: "bowl",
    calories: 300,
    range: "250-350 kcal",
    profile: "fasting",
    aliases: ["peanut amti"],
  }),
  maharashtrianFood({
    name: "Sweet Potato Khichdi",
    category: "Fasting Foods",
    servingUnit: "bowl",
    calories: 250,
    range: "200-300 kcal",
    profile: "fasting",
    aliases: ["ratala khichdi"],
  }),
  maharashtrianFood({
    name: "Farali Pattice",
    category: "Fasting Foods",
    servingUnit: "piece",
    calories: 215,
    range: "180-250 kcal",
    profile: "fasting",
    aliases: ["farali patties"],
  }),

  // Traditional Maharashtrian Thali
  maharashtrianFood({
    name: "Traditional Maharashtrian Thali",
    category: "Maharashtrian Thali",
    servingUnit: "serving",
    calories: 1025,
    range: "950-1100 kcal",
    profile: "thali",
    note: "Approximate thali with jowar bhakri, pithla or zunka, amti, rice, vegetable, and buttermilk.",
  }),
];

const dailyMaharashtrianFoods = [
  // Daily Breakfast Additions
  maharashtrianFood({
    name: "Bread Butter",
    category: "Daily Breakfast",
    servingUnit: "serving",
    calories: 215,
    range: "180-250 kcal",
    profile: "breakfast",
    serving: "2 slices",
    aliases: ["buttered bread"],
  }),
  maharashtrianFood({
    name: "Bread Omelette",
    category: "Daily Breakfast",
    servingUnit: "serving",
    calories: 300,
    range: "250-350 kcal",
    profile: "egg",
  }),
  maharashtrianFood({
    name: "Boiled Egg",
    category: "Daily Non-Vegetarian",
    servingUnit: "piece",
    calories: 75,
    range: "70-80 kcal",
    profile: "egg",
    serving: "1 egg",
    aliases: ["boiled eggs"],
  }),

  // Daily Lunch & Dinner Additions
  maharashtrianFood({
    name: "Dal Rice",
    category: "Daily Lunch & Dinner",
    servingUnit: "plate",
    calories: 475,
    range: "400-550 kcal",
    profile: "riceDish",
    aliases: ["dal bhaat"],
  }),
  maharashtrianFood({
    name: "Amti Rice",
    category: "Daily Lunch & Dinner",
    servingUnit: "plate",
    calories: 525,
    range: "450-600 kcal",
    profile: "riceDish",
    aliases: ["amti bhaat"],
  }),
  maharashtrianFood({
    name: "Rice",
    category: "Daily Lunch & Dinner",
    servingUnit: "cup",
    calories: 225,
    range: "200-250 kcal",
    profile: "riceDish",
    aliases: ["cooked rice", "steamed rice"],
  }),
  maharashtrianFood({
    name: "Moong Usal",
    category: "Daily Lunch & Dinner",
    servingUnit: "bowl",
    calories: 200,
    range: "150-250 kcal",
    profile: "dalCurry",
    aliases: ["mung usal"],
  }),
  maharashtrianFood({
    name: "Chana Usal",
    category: "Daily Lunch & Dinner",
    servingUnit: "bowl",
    calories: 270,
    range: "220-320 kcal",
    profile: "dalCurry",
  }),
  maharashtrianFood({
    name: "Aloo Bhaji",
    category: "Daily Lunch & Dinner",
    servingUnit: "bowl",
    calories: 200,
    range: "150-250 kcal",
    profile: "vegCurry",
    aliases: ["batata bhaji", "potato bhaji"],
  }),
  maharashtrianFood({
    name: "Bhindi Bhaji",
    category: "Daily Lunch & Dinner",
    servingUnit: "bowl",
    calories: 160,
    range: "120-200 kcal",
    profile: "vegCurry",
    aliases: ["okra bhaji"],
  }),
  maharashtrianFood({
    name: "Cabbage Bhaji",
    category: "Daily Lunch & Dinner",
    servingUnit: "bowl",
    calories: 115,
    range: "80-150 kcal",
    profile: "vegCurry",
  }),
  maharashtrianFood({
    name: "Methi Bhaji",
    category: "Daily Lunch & Dinner",
    servingUnit: "bowl",
    calories: 115,
    range: "80-150 kcal",
    profile: "vegCurry",
    aliases: ["fenugreek bhaji"],
  }),
  maharashtrianFood({
    name: "Palak Bhaji",
    category: "Daily Lunch & Dinner",
    servingUnit: "bowl",
    calories: 115,
    range: "80-150 kcal",
    profile: "vegCurry",
    aliases: ["spinach bhaji"],
  }),
  maharashtrianFood({
    name: "Tondli Bhaji",
    category: "Daily Lunch & Dinner",
    servingUnit: "bowl",
    calories: 140,
    range: "100-180 kcal",
    profile: "vegCurry",
    aliases: ["ivy gourd bhaji"],
  }),
  maharashtrianFood({
    name: "Dudhi Bhaji",
    category: "Daily Lunch & Dinner",
    servingUnit: "bowl",
    calories: 110,
    range: "80-140 kcal",
    profile: "vegCurry",
    aliases: ["lauki bhaji", "bottle gourd bhaji"],
  }),

  // Common Maharashtrian Vegetables
  maharashtrianFood({
    name: "Batata Rassa",
    category: "Common Maharashtrian Vegetables",
    servingUnit: "bowl",
    calories: 215,
    range: "180-250 kcal",
    profile: "vegCurry",
    aliases: ["potato rassa"],
  }),
  maharashtrianFood({
    name: "Flower Bhaji",
    category: "Common Maharashtrian Vegetables",
    servingUnit: "bowl",
    calories: 140,
    range: "100-180 kcal",
    profile: "vegCurry",
    aliases: ["cauliflower bhaji", "phool gobi bhaji"],
  }),
  maharashtrianFood({
    name: "Gavar Bhaji",
    category: "Common Maharashtrian Vegetables",
    servingUnit: "bowl",
    calories: 115,
    range: "80-150 kcal",
    profile: "vegCurry",
    aliases: ["cluster beans bhaji"],
  }),
  maharashtrianFood({
    name: "Walachi Usal",
    category: "Common Maharashtrian Vegetables",
    servingUnit: "bowl",
    calories: 230,
    range: "180-280 kcal",
    profile: "dalCurry",
    aliases: ["field bean usal", "vaal usal"],
  }),
  maharashtrianFood({
    name: "Chawli Bhaji",
    category: "Common Maharashtrian Vegetables",
    servingUnit: "bowl",
    calories: 140,
    range: "100-180 kcal",
    profile: "vegCurry",
    aliases: ["cowpea bhaji"],
  }),
  maharashtrianFood({
    name: "Karela Bhaji",
    category: "Common Maharashtrian Vegetables",
    servingUnit: "bowl",
    calories: 115,
    range: "80-150 kcal",
    profile: "vegCurry",
    aliases: ["bitter gourd bhaji"],
  }),
  maharashtrianFood({
    name: "Mix Vegetable",
    category: "Common Maharashtrian Vegetables",
    servingUnit: "bowl",
    calories: 160,
    range: "120-200 kcal",
    profile: "vegCurry",
    aliases: ["mixed vegetable bhaji"],
  }),
  maharashtrianFood({
    name: "Vatana Usal",
    category: "Common Maharashtrian Vegetables",
    servingUnit: "bowl",
    calories: 230,
    range: "180-280 kcal",
    profile: "dalCurry",
    aliases: ["peas usal"],
  }),
  maharashtrianFood({
    name: "Green Peas Curry",
    category: "Common Maharashtrian Vegetables",
    servingUnit: "bowl",
    calories: 215,
    range: "180-250 kcal",
    profile: "dalCurry",
    aliases: ["vatana curry"],
  }),
  maharashtrianFood({
    name: "Tomato Saar",
    category: "Common Maharashtrian Vegetables",
    servingUnit: "bowl",
    calories: 75,
    range: "50-100 kcal",
    profile: "soup",
    aliases: ["tomato saar"],
  }),

  // Daily Snacks
  maharashtrianFood({
    name: "Chivda",
    category: "Daily Snacks",
    servingSize: 50,
    servingUnit: "g",
    calories: 250,
    range: "220-280 kcal",
    profile: "friedSnack",
    aliases: ["chiwda"],
  }),
  maharashtrianFood({
    name: "Bhel",
    category: "Daily Snacks",
    servingUnit: "plate",
    calories: 300,
    range: "250-350 kcal",
    profile: "streetFood",
    aliases: ["bhel puri"],
  }),
  maharashtrianFood({
    name: "Roasted Peanuts",
    category: "Daily Snacks",
    servingSize: 30,
    servingUnit: "g",
    calories: 180,
    range: "170-190 kcal",
    profile: "nutsSnack",
  }),
  maharashtrianFood({
    name: "Peanuts Jaggery Chikki",
    category: "Daily Snacks",
    servingUnit: "piece",
    calories: 100,
    range: "80-120 kcal",
    profile: "nutsSnack",
    aliases: ["peanut chikki", "groundnut chikki"],
  }),
  maharashtrianFood({
    name: "Khakhra",
    category: "Daily Snacks",
    servingUnit: "piece",
    calories: 80,
    range: "60-100 kcal",
    profile: "breakfast",
  }),
  maharashtrianFood({
    name: "Coconut Water",
    category: "Daily Snacks",
    servingUnit: "glass",
    calories: 50,
    range: "40-60 kcal",
    profile: "fruit",
  }),

  // Daily Dairy Foods
  maharashtrianFood({
    name: "Milk (250 ml)",
    category: "Daily Dairy",
    servingUnit: "glass",
    calories: 145,
    range: "120-170 kcal",
    profile: "dairy",
    aliases: ["milk"],
  }),
  maharashtrianFood({
    name: "Curd",
    category: "Daily Dairy",
    servingUnit: "bowl",
    calories: 115,
    range: "80-150 kcal",
    profile: "dairy",
    aliases: ["dahi"],
  }),
  maharashtrianFood({
    name: "Paneer",
    category: "Daily Dairy",
    servingSize: 100,
    servingUnit: "g",
    calories: 275,
    range: "250-300 kcal",
    profile: "dairy",
    aliases: ["cottage cheese"],
  }),
  maharashtrianFood({
    name: "Ghee",
    category: "Daily Dairy",
    servingUnit: "tbsp",
    calories: 120,
    range: "120 kcal",
    profile: "fatOnly",
    aliases: ["clarified butter"],
  }),
  maharashtrianFood({
    name: "Butter",
    category: "Daily Dairy",
    servingUnit: "tbsp",
    calories: 100,
    range: "100 kcal",
    profile: "fatOnly",
  }),

  // Daily Non-Vegetarian Foods
  maharashtrianFood({
    name: "Omelette",
    category: "Daily Non-Vegetarian",
    servingUnit: "serving",
    calories: 215,
    range: "180-250 kcal",
    profile: "egg",
    serving: "2 eggs",
  }),
  maharashtrianFood({
    name: "Egg Curry",
    category: "Daily Non-Vegetarian",
    servingUnit: "bowl",
    calories: 250,
    range: "200-300 kcal",
    profile: "egg",
  }),
  maharashtrianFood({
    name: "Chicken Sukka",
    category: "Daily Non-Vegetarian",
    servingSize: 100,
    servingUnit: "g",
    calories: 325,
    range: "250-400 kcal",
    profile: "meat",
    aliases: ["chicken sukha"],
  }),
  maharashtrianFood({
    name: "Fish Curry",
    category: "Daily Non-Vegetarian",
    servingUnit: "bowl",
    calories: 275,
    range: "200-350 kcal",
    profile: "fish",
  }),
  maharashtrianFood({
    name: "Fish Fry",
    category: "Daily Non-Vegetarian",
    servingSize: 100,
    servingUnit: "g",
    calories: 325,
    range: "250-400 kcal",
    profile: "fish",
  }),
  maharashtrianFood({
    name: "Mutton Curry",
    category: "Daily Non-Vegetarian",
    servingUnit: "bowl",
    calories: 400,
    range: "300-500 kcal",
    profile: "meat",
  }),

  // Fruits Commonly Eaten in Maharashtra
  maharashtrianFood({
    name: "Muskmelon",
    category: "Fruits Common in Maharashtra",
    servingUnit: "serving",
    calories: 50,
    range: "40-60 kcal",
    profile: "fruit",
    aliases: ["kharbuja", "cantaloupe"],
  }),

  // Lowest-Calorie Daily Foods
  maharashtrianFood({
    name: "Cucumber Salad",
    category: "Lowest-Calorie Daily Foods",
    servingSize: 100,
    servingUnit: "g",
    calories: 15,
    range: "15 kcal per 100 g",
    profile: "salad",
  }),
  maharashtrianFood({
    name: "Tomato Salad",
    category: "Lowest-Calorie Daily Foods",
    servingSize: 100,
    servingUnit: "g",
    calories: 20,
    range: "20 kcal per 100 g",
    profile: "salad",
  }),
];

// Bachelor / hostel "cheat meal" street foods — the quick, indulgent stuff
// (Maggi, bajji, rolls, chaat, fried rice, momos…). Values are per-serving
// estimates; grouped under one category so they're easy to browse.
const cheatMeals = [
  { name: "Maggi Masala Noodles", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 350, protein: 8, carbs: 50, fat: 13, fiber: 2, calcium: 20, iron: 2, sodium: 900, potassium: 150, vitaminC: 1, vitaminA: 50, description: "One plate of masala Maggi (1 pack).", aliases: ["maggi", "masala noodles", "2 minute noodles", "instant noodles"] },
  { name: "Cheese Maggi", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 460, protein: 13, carbs: 52, fat: 22, fiber: 2, calcium: 180, iron: 2, sodium: 1000, potassium: 180, vitaminC: 1, vitaminA: 120, description: "Maggi loaded with cheese.", aliases: ["cheese maggi"] },
  { name: "Egg Maggi", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 430, protein: 15, carbs: 50, fat: 18, fiber: 2, calcium: 40, iron: 2.5, sodium: 950, potassium: 200, vitaminC: 1, vitaminA: 130, description: "Maggi cooked with egg.", aliases: ["egg maggi", "anda maggi"] },
  { name: "Vegetable Bajji (Bhaji)", category: "Cheat Meals", servingSize: 1, servingUnit: "piece", calories: 100, protein: 2, carbs: 10, fat: 6, fiber: 1, calcium: 10, iron: 0.6, sodium: 160, potassium: 90, vitaminC: 2, vitaminA: 40, description: "One deep-fried gram-flour fritter.", aliases: ["bajje", "bajji", "bhaji", "mirchi bajji", "bonda"] },
  { name: "Batata Vada", category: "Cheat Meals", servingSize: 1, servingUnit: "piece", calories: 145, protein: 3, carbs: 18, fat: 7, fiber: 2, calcium: 15, iron: 0.8, sodium: 260, potassium: 200, vitaminC: 5, vitaminA: 30, description: "Spiced potato fritter.", aliases: ["aloo vada", "potato vada"] },
  { name: "Pav Bhaji", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 400, protein: 9, carbs: 52, fat: 18, fiber: 6, calcium: 60, iron: 2.5, sodium: 780, potassium: 520, vitaminC: 20, vitaminA: 450, description: "Buttery mashed veg bhaji with two pav.", aliases: ["pav bhaji"] },
  { name: "Pani Puri", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 140, protein: 3, carbs: 26, fat: 3, fiber: 2, calcium: 25, iron: 1, sodium: 420, potassium: 180, vitaminC: 6, vitaminA: 80, description: "Six pani puri with spiced water.", aliases: ["golgappa", "puchka", "gol gappe", "gupchup"] },
  { name: "Sev Puri", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 250, protein: 5, carbs: 38, fat: 9, fiber: 3, calcium: 35, iron: 1.5, sodium: 560, potassium: 260, vitaminC: 10, vitaminA: 140, description: "Crispy puri chaat topped with sev.", aliases: ["sev puri"] },
  { name: "Dahi Puri", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 280, protein: 6, carbs: 40, fat: 10, fiber: 3, calcium: 90, iron: 1.4, sodium: 520, potassium: 280, vitaminC: 8, vitaminA: 150, description: "Puri chaat with curd and chutneys.", aliases: ["dahi puri", "dahi batata puri"] },
  { name: "Ragda Pattice", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 330, protein: 10, carbs: 48, fat: 11, fiber: 8, calcium: 70, iron: 2.6, sodium: 620, potassium: 420, vitaminC: 6, vitaminA: 120, description: "Potato patties topped with white-pea ragda.", aliases: ["ragda pattice", "ragda patties"] },
  { name: "Aloo Tikki", category: "Cheat Meals", servingSize: 1, servingUnit: "piece", calories: 150, protein: 3, carbs: 22, fat: 6, fiber: 2, calcium: 18, iron: 0.9, sodium: 300, potassium: 220, vitaminC: 8, vitaminA: 60, description: "Shallow-fried spiced potato patty.", aliases: ["aloo tikki", "potato tikki"] },
  { name: "Kachori", category: "Cheat Meals", servingSize: 1, servingUnit: "piece", calories: 200, protein: 4, carbs: 24, fat: 10, fiber: 2, calcium: 16, iron: 1, sodium: 280, potassium: 130, vitaminC: 1, vitaminA: 20, description: "Flaky deep-fried stuffed kachori.", aliases: ["pyaaz kachori", "khasta kachori"] },
  { name: "Dahi Vada", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 230, protein: 8, carbs: 30, fat: 8, fiber: 2, calcium: 140, iron: 1.2, sodium: 420, potassium: 220, vitaminC: 2, vitaminA: 110, description: "Two lentil vadas in spiced curd.", aliases: ["dahi vada", "dahi bhalla"] },
  { name: "Veg Frankie (Kathi Roll)", category: "Cheat Meals", servingSize: 1, servingUnit: "piece", calories: 300, protein: 8, carbs: 40, fat: 12, fiber: 3, calcium: 50, iron: 2, sodium: 560, potassium: 220, vitaminC: 6, vitaminA: 120, description: "Veg-stuffed rolled wrap.", aliases: ["frankie", "kathi roll", "veg roll", "veg wrap"] },
  { name: "Egg Roll", category: "Cheat Meals", servingSize: 1, servingUnit: "piece", calories: 360, protein: 14, carbs: 40, fat: 16, fiber: 2, calcium: 50, iron: 2.4, sodium: 620, potassium: 260, vitaminC: 5, vitaminA: 180, description: "Kolkata-style egg roll.", aliases: ["egg roll", "anda roll"] },
  { name: "Chicken Roll", category: "Cheat Meals", servingSize: 1, servingUnit: "piece", calories: 400, protein: 22, carbs: 40, fat: 17, fiber: 2, calcium: 50, iron: 2.4, sodium: 680, potassium: 320, vitaminC: 5, vitaminA: 180, description: "Chicken-stuffed roll.", aliases: ["chicken roll", "chicken kathi roll"] },
  { name: "Bun Maska", category: "Cheat Meals", servingSize: 1, servingUnit: "piece", calories: 220, protein: 5, carbs: 32, fat: 8, fiber: 1, calcium: 40, iron: 1.2, sodium: 320, potassium: 90, vitaminC: 0, vitaminA: 140, description: "Soft bun with a thick layer of butter.", aliases: ["bun maska", "maska pav", "maska bun"] },
  { name: "Bombay Grilled Sandwich", category: "Cheat Meals", servingSize: 1, servingUnit: "piece", calories: 280, protein: 7, carbs: 38, fat: 11, fiber: 4, calcium: 80, iron: 1.6, sodium: 560, potassium: 320, vitaminC: 14, vitaminA: 220, description: "Veg grilled sandwich with chutney.", aliases: ["grilled sandwich", "veg sandwich", "bombay sandwich"] },
  { name: "Cheese Grilled Sandwich", category: "Cheat Meals", servingSize: 1, servingUnit: "piece", calories: 380, protein: 12, carbs: 40, fat: 19, fiber: 4, calcium: 260, iron: 1.6, sodium: 720, potassium: 320, vitaminC: 12, vitaminA: 260, description: "Cheesy grilled sandwich.", aliases: ["cheese sandwich"] },
  { name: "French Fries", category: "Cheat Meals", servingSize: 100, servingUnit: "g", calories: 312, protein: 3.4, carbs: 41, fat: 15, fiber: 3.8, calcium: 12, iron: 0.8, sodium: 210, potassium: 580, vitaminC: 9, vitaminA: 0, description: "Deep-fried potato fries.", aliases: ["fries", "finger chips"] },
  { name: "Veg Manchurian", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 320, protein: 8, carbs: 42, fat: 13, fiber: 4, calcium: 50, iron: 1.8, sodium: 820, potassium: 320, vitaminC: 12, vitaminA: 180, description: "Fried veg balls in Indo-Chinese gravy.", aliases: ["manchurian", "veg manchurian"] },
  { name: "Veg Hakka Noodles", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 350, protein: 9, carbs: 56, fat: 10, fiber: 4, calcium: 40, iron: 2, sodium: 880, potassium: 260, vitaminC: 10, vitaminA: 220, description: "Stir-fried Indo-Chinese noodles.", aliases: ["hakka noodles", "chowmein", "chow mein", "noodles"] },
  { name: "Veg Fried Rice", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 380, protein: 8, carbs: 62, fat: 11, fiber: 3, calcium: 40, iron: 2, sodium: 820, potassium: 300, vitaminC: 8, vitaminA: 260, description: "Indo-Chinese fried rice.", aliases: ["fried rice"] },
  { name: "Schezwan Fried Rice", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 410, protein: 9, carbs: 64, fat: 13, fiber: 3, calcium: 42, iron: 2.1, sodium: 980, potassium: 320, vitaminC: 10, vitaminA: 280, description: "Spicy schezwan fried rice.", aliases: ["schezwan rice", "szechuan fried rice"] },
  { name: "Chilli Paneer", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 350, protein: 16, carbs: 24, fat: 21, fiber: 2, calcium: 320, iron: 1, sodium: 880, potassium: 240, vitaminC: 10, vitaminA: 300, description: "Indo-Chinese chilli paneer.", aliases: ["chilli paneer"] },
  { name: "Veg Momos", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 250, protein: 7, carbs: 44, fat: 5, fiber: 3, calcium: 40, iron: 1.6, sodium: 560, potassium: 200, vitaminC: 6, vitaminA: 120, description: "Six steamed veg momos.", aliases: ["momos", "momo", "dimsum"] },
  { name: "Fried Momos", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 330, protein: 7, carbs: 46, fat: 13, fiber: 3, calcium: 40, iron: 1.6, sodium: 620, potassium: 210, vitaminC: 6, vitaminA: 120, description: "Six fried momos.", aliases: ["fried momos"] },
  { name: "Veg Burger", category: "Cheat Meals", servingSize: 1, servingUnit: "piece", calories: 330, protein: 9, carbs: 46, fat: 12, fiber: 4, calcium: 80, iron: 2.4, sodium: 620, potassium: 300, vitaminC: 6, vitaminA: 140, description: "Aloo-tikki veg burger.", aliases: ["burger", "aloo tikki burger", "veg burger"] },
  { name: "Cheese Pizza (Slice)", category: "Cheat Meals", servingSize: 1, servingUnit: "piece", calories: 285, protein: 12, carbs: 36, fat: 11, fiber: 2, calcium: 200, iron: 2, sodium: 640, potassium: 220, vitaminC: 4, vitaminA: 200, description: "One slice of cheese pizza.", aliases: ["pizza", "cheese pizza"] },
  { name: "Bread Omelette", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 290, protein: 12, carbs: 26, fat: 15, fiber: 2, calcium: 60, iron: 2, sodium: 560, potassium: 180, vitaminC: 2, vitaminA: 180, description: "Omelette with bread slices.", aliases: ["bread omelette", "anda bread"] },
  { name: "Egg Bhurji Pav", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 340, protein: 15, carbs: 34, fat: 16, fiber: 2, calcium: 80, iron: 2.4, sodium: 640, potassium: 220, vitaminC: 6, vitaminA: 220, description: "Scrambled spiced egg with pav.", aliases: ["egg bhurji", "anda bhurji pav"] },
  { name: "Maggi Pakora", category: "Cheat Meals", servingSize: 1, servingUnit: "plate", calories: 420, protein: 9, carbs: 48, fat: 21, fiber: 2, calcium: 30, iron: 2, sodium: 880, potassium: 170, vitaminC: 1, vitaminA: 60, description: "Deep-fried Maggi fritters.", aliases: ["maggi pakora", "maggi bhaji"] },
];

const seedFoods = [
  ...indianFoods,
  ...extendedIndianFoods,
  ...maharashtrianFoods,
  ...dailyMaharashtrianFoods,
  ...cheatMeals,
];

export const seedDatabase = async () => {
  try {
    const operations = seedFoods.map((food) => ({
      updateOne: {
        filter: { name: food.name, isCustom: { $ne: true } },
        update: { $set: { ...food, isCustom: false, createdBy: null } },
        upsert: true,
      },
    }));

    const result = await Food.bulkWrite(operations);
    console.log(
      `Seeded Indian foods. Inserted: ${result.upsertedCount}, updated: ${result.modifiedCount}`,
    );
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
};

export const connectDatabase = async () => {
  try {
    const mongoUrl =
      process.env.DATABASE_URL || "mongodb://localhost:27017/calorie-tracker";
    await mongoose.connect(mongoUrl, { serverSelectionTimeoutMS: 10000 });
    console.log("Connected to MongoDB");
    await seedDatabase();
  } catch (error) {
    const usingDefaultLocalUrl = !process.env.DATABASE_URL;
    const message = error?.message || "";
    const isConnectionRefused = message.includes("ECONNREFUSED");
    const isAtlasAccessBlocked =
      error?.name === "MongooseServerSelectionError" ||
      message.includes("whitelist") ||
      message.includes("IP that isn't whitelisted");

    if (usingDefaultLocalUrl && isConnectionRefused) {
      console.error(
        [
          "MongoDB connection error: no local MongoDB server is running at mongodb://localhost:27017.",
          "Fix: create Backend/.env with your MongoDB Atlas DATABASE_URL, or install/start MongoDB locally.",
          "Start command: npm run dev",
        ].join("\n"),
      );
      error.isDatabaseSetupError = true;
    } else if (isAtlasAccessBlocked) {
      console.error(
        [
          "MongoDB connection error: could not reach the Atlas cluster.",
          "Most common cause: your current IP is not in the cluster's Network Access allowlist.",
          "Fix: MongoDB Atlas → Network Access → Add IP Address → add your current IP (or 0.0.0.0/0 for development).",
          "Also verify the DATABASE_URL credentials in Backend/.env and your internet connection.",
        ].join("\n"),
      );
      error.isDatabaseSetupError = true;
    } else {
      console.error("MongoDB connection error:", error);
    }

    throw error;
  }
};

export const disconnectDatabase = async () => {
  try {
    await mongoose.disconnect();
    console.log("Disconnected from MongoDB");
  } catch (error) {
    console.error("Error disconnecting from MongoDB:", error);
    throw error;
  }
};
